version: '3'

# valores setados como variavel ${} , dever ser informadas no arquivo .env

# Contaniner api adonis
services:
  api:
    container_name: docker-lab-api
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
    networks: 
      - docker-adonis-api   
    depends_on:
        - mysqlsrv 

# Container Mysql
  mysqlsrv:    
    container_name: mysql-docker
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:        
        - "${DB_PORT}:${DB_PORT}"
    volumes:
      - /home/fernando/volumes/mysql:/var/lib/mysql  
    networks: 
      - docker-adonis-api

      # Network
networks:
  docker-adonis-api:
