-- create database test
CREATE DATABASE IF NOT EXISTS '${DB_DATABASE_TEST}' CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER '${DB_USER_TEST}'@'%' IDENTIFIED BY '${DB_PASSWORD_TEST}';

GRANT ALL PRIVILEGES ON  '${DB_DATABASE_TEST}'. * TO '${DB_USER_TEST}'@'%';

FLUSH PRIVILEGES;